export const mockProductList2 = [
  {
    id: 's-1',
    title: 'Guchi',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike Air trainers in pink, yellow and purple',
    src: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    price: 190,
    rating: 4,
  },
  {
    id: 's-2',
    title: 'Chanel',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Converse in red and black',
    src: 'https://images.unsplash.com/photo-1604001307862-2d953b875079?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=927&q=80',
    price: 110,
    rating: 4,
  },
  {
    id: 's-3',
    title: 'Jimmy Shoes',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Yeezy in white',
    src: 'https://images.unsplash.com/photo-1565201053376-de8b6fd6aa66?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-4',
    title: 'Wed Me',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike M35',
    src: 'https://images.unsplash.com/photo-1552419272-b0d8e736ea2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=934&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-5',
    title: 'Rub Sands',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike Air Classic in white',
    src: 'https://images.unsplash.com/photo-1534653299134-96a171b61581?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1782&q=80',
    price: 190,
    rating: 4,
  },
  {
    id: 's-6',
    title: 'Wedgers',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Adidas Ultra in yellow',
    src: 'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1300&q=80',
    price: 110,
    rating: 4,
  },

  {
    id: 's-7',
    title: 'Zara',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair Nike Air 2 in black and red',
    src: 'https://images.unsplash.com/photo-1559669615-c03ba52afc37?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1590&q=80',
    price: 190,
    rating: 4,
  },
  {
    id: 's-8',
    title: 'Skins',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike Louis in beige nad brown',
    src: 'https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80',
    price: 110,
    rating: 4,
  },
  {
    id: 's-9',
    title: 'Pebbles',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike Air Force 1 in red and white',
    src: 'https://images.unsplash.com/photo-1582738412120-7f6baeff4da9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=934&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-10',
    title: 'Silver Slips',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike Nike Magic in black',
    src: 'https://images.unsplash.com/photo-1584126321238-9599c6388dfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=934&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-11',
    title: 'Lagoon',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair Nike Jordans in blue, black and white',
    src: 'https://images.unsplash.com/photo-1579727027525-352607d8dc49?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=934&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-12',
    title: 'Dianas',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Converse 2 in black with red heart',
    src: 'https://images.unsplash.com/photo-1515651673377-6abc94e6e889?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1266&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-13',
    title: 'Beckers',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Nike Nike Magic in black',
    src: 'https://images.unsplash.com/photo-1571859856639-d54ab2c18ba0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=800&q=60',
    price: 280,
    rating: 4,
  },
  {
    id: 's-14',
    title: 'Doc Martins',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair Nike Jordans in blue, black and white',
    src: 'https://images.unsplash.com/photo-1614594678451-41c1bf1ba45e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80',
    price: 280,
    rating: 4,
  },
  {
    id: 's-15',
    title: 'Camper',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus',
    alt: 'Pair of Converse 2 in black with red heart',
    src: 'https://images.unsplash.com/photo-1499013819532-e4ff41b00669?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1600&q=80',
    price: 280,
    rating: 4,
  },
];
